CheatNoteMaker/CheatNoteMaker/Models/CheatNotes/CheatNote.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using CheatNoteMaker.Models.Common;

namespace CheatNoteMaker.Models.CheatNotes
{
    public class CheatNote : ObjectBase
    {
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Название")]
        public string Name { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Описание")]
        public string Description { get; set; }

        public virtual ICollection<CheatNoteItem> Items { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}

CheatNoteMaker/CheatNoteMaker/Models/CheatNotes/CheatNoteGeneratedHtml.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CheatNoteMaker.Models.CheatNotes
{
    public class CheatNoteGeneratedHtml : CheatNoteGeneratedHtmlInfo
    {
        [Required]
        [Column(TypeName = "ntext")]
        public string Html { get; set; }
    }
}

CheatNoteMaker/CheatNoteMaker/Models/CheatNotes/CheatNoteGeneratedHtmlInfo.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CheatNoteMaker.Models.CheatNotes
{
    public class CheatNoteGeneratedHtmlInfo
    {
        public CheatNoteGeneratedHtmlInfo()
        {
            DateCreated = DateTime.Now;
        }

        public int Id { get; set; }

        public DateTime DateCreated { get; set; }

        [Required]
        public int CheatNoteId { get; set; }

        [Required]
        public string FileName { get; set; }

        [Required]
        public long Size { get; set; }
    }
}

CheatNoteMaker/CheatNoteMaker/Models/CheatNotes/CheatNoteItem.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using CheatNoteMaker.Models.Common;

namespace CheatNoteMaker.Models.CheatNotes
{
    public class CheatNoteItem : ObjectBase
    {
        [Required]
        public int CheatNoteId { get; set; }

        [Required]
        [Display(Name = "Номер вопроса")]
        public int Position { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Текст вопроса")]
        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Текст ответа")]
        [Column(TypeName = "ntext")]
        public string Content { get; set; }

        public virtual new string ToString()
        {
            return string.Format("{0}. {1}", Position, Title);
        }
    }
}

CheatNoteMaker/CheatNoteMaker/Controllers/CheatNotes/BaseController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Security;
using System.Web.Mvc;

using CheatNoteMaker.BusinessLogic.Extensions;
using CheatNoteMaker.BusinessLogic.Security;
using CheatNoteMaker.Models;
using CheatNoteMaker.Models.Common;
using CheatNoteMaker.Models.Users;

namespace CheatNoteMaker.Controllers.CheatNotes
{
    public class BaseController : Controller
    {
        protected void SetInstanceDeleted<T>(Func<CheatNotesContext, IDbSet<T>> getInstances, int id, bool instanceDeleted)
            where T : ObjectBase
        {
            using (var db = new CheatNotesContext())
            {
                var instance = getInstances(db).Get(id);

                if (instance != null)
                {
                    if (instanceDeleted)
                    {
                        instance.DateDeleted = DateTime.Now;
                        instance.DeletedById = GetCurrentUserId();
                    }
                    else
                    {
                        instance.DateDeleted = null;
                        instance.DateModified = DateTime.Now;
                        instance.ModifiedById = GetCurrentUserId();
                    }
                }

                db.Entry(instance).State = EntityState.Modified;
                db.SaveChanges();
            }
        }

        protected UserInfo GetCurrentUser()
        {
            return UserPermissionsManager.GetUserInfo(User.Identity.Name);
        }

        protected int? GetCurrentUserId()
        {
            var user = UserPermissionsManager.GetUserInfo(User.Identity.Name);

            return user != null ? (int?)user.Id : null;
        }

        protected UserPermissions GetCurrentUserPermissions()
        {
            return UserPermissionsManager.GetUserPermissions(User.Identity.Name) ?? UserPermissions.GetReaderPermissions();
        }

        protected void ThrowIfNotPermitted(Func<UserPermissions, bool> getOperation)
        {
            if (!IsPermitted(getOperation))
            {
                throw new SecurityException("У Вас нет доступа к этой операции. Обратитесь к администратору.");
            }
        }

        protected bool IsPermitted(Func<UserPermissions, bool> getOperation)
        {
            return UserPermissionsManager.IsPermitted(User.Identity.Name, getOperation);
        }

        protected string CreateUserInfo(string userName)
        {
            return UserPermissionsManager.CreateUserInfo(userName);
        }
    }
}

CheatNoteMaker/CheatNoteMaker/Controllers/CheatNotes/CheatNoteHtmlGeneratorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

using CheatNoteMaker.BusinessLogic.CustomAttributes;
using CheatNoteMaker.BusinessLogic.Extensions;
using CheatNoteMaker.BusinessLogic.HtmlGenerator;
using CheatNoteMaker.Models;
using CheatNoteMaker.Models.CheatNotes;

using Ionic.Zip;

namespace CheatNoteMaker.Controllers.CheatNotes
{
    public class CheatNoteHtmlGeneratorController : BaseController
    {
        private const float FileSizeMultiplier = 2.1f;

        [Authorize]
        [PermissionRequired]
        public ActionResult GenerateHtmlFiles(int id)
        {
            using (var db = new CheatNotesContext())
            {
                var cheatNote = db.CheatNotes.Get(id);

                var model = new GenerateHtmlFilesModel(cheatNote)
                                {
                                    PartSize = 250,
                                    HtmlInfos = GetGeneratedHtmls(db, id)
                                };

                return View(model);
            }
        }

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        public ActionResult GenerateHtmlFiles(GenerateHtmlFilesModel model)
        {
            using (var db = new CheatNotesContext())
            {
                var cheatNote = db.CheatNotes.Get(model.CheatNoteId);
                var partSize = !model.PartSize.HasValue || model.PartSize.Value <= 100 ? null : (long?)(model.PartSize * 1024 / FileSizeMultiplier);

                model.HtmlInfos = UpdateCheatNoteHtmls(db, model.CheatNoteId, CheatNoteHtmlGenerator.GenerateHtmlFiles(model.FileName, cheatNote, partSize));
                
                return View(model);
            }
        }
        
        public ActionResult Download(int id)
        {
            using (var db = new CheatNotesContext())
            {
                var html = db.CheatNoteHtmls.FirstOrDefault(x => x.Id == id);

                if (html == null)
                {
                    return null;
                }

                return File(TextToBytes(html.Html), "text/html", html.FileName);
            }
        }

        public ActionResult DownloadZip(int cnid)
        {
            using (var db = new CheatNotesContext())
            {
                var htmls = GetGeneratedHtmls(db, cnid);

                if (!htmls.Any())
                {
                    return null;
                }

                return File(CreateZip(htmls), "application/zip", string.Format("CheatNote_{0}.zip", cnid));
            }
        }

        private static byte[] CreateZip(IEnumerable<CheatNoteGeneratedHtml> htmls)
        {
            using (var ms = new MemoryStream())
            {
                using (var zip = new ZipFile())
                {
                    foreach (var html in htmls)
                    {
                        zip.AddEntry(html.FileName, TextToBytes(html.Html));
                    }

                    zip.Save(ms);
                }

                return ms.ToArray();
            }
        }

        private static IEnumerable<CheatNoteGeneratedHtml> UpdateCheatNoteHtmls(CheatNotesContext db, int cheatNoteId, IEnumerable<CheatNoteGeneratedHtml> htmls)
        {
            foreach (var html in htmls)
            {
                html.CheatNoteId = cheatNoteId;
                html.Size = TextToBytes(html.Html).Length;
            }

            var existing = GetGeneratedHtmls(db, cheatNoteId);

            if (existing.Any())
            {
                db.CheatNoteHtmls.RemoveRange(existing);
            }

            var result = db.CheatNoteHtmls.AddRange(htmls);

            db.SaveChanges();

            return result;
        }

        private static IEnumerable<CheatNoteGeneratedHtml> GetGeneratedHtmls(CheatNotesContext db, int cheatNoteId)
        {
            return db.CheatNoteHtmls.Where(html => html.CheatNoteId == cheatNoteId).ToList();
        }

        private static byte[] TextToBytes(string text)
        {
            return new UTF8Encoding().GetBytes(text);
        }

        //private static byte[] TextToBytes(string text)
        //{
        //    if (string.IsNullOrWhiteSpace(text))
        //    {
        //        return new byte[0];
        //    }

        //    using (var stream = new MemoryStream())
        //    {
        //        using (var sw = new StreamWriter(stream, Encoding.UTF8))
        //        {
        //            sw.Write(text);
        //            sw.Close();

        //            return stream.ToArray();
        //        }
        //    }
        //}
    }
}

CheatNoteMaker/CheatNoteMaker/Controllers/CheatNotes/CheatNoteItemsController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using CheatNoteMaker.BusinessLogic.CustomAttributes;
using CheatNoteMaker.Models;
using CheatNoteMaker.Models.CheatNotes;
using CheatNoteMaker.BusinessLogic.Extensions;

namespace CheatNoteMaker.Controllers.CheatNotes
{
    public class CheatNoteItemsController : BaseController
    {
        //
        // GET: /CheatNoteItems/List
        [Authorize]
        public ActionResult List(int? cnid, bool? showDeleted)
        {
            if (!cnid.HasValue)
            {
                return RedirectToAction("Error", "Home");
            }

            using (var db = new CheatNotesContext())
            {
                if (!db.CheatNotes.Any(x => x.Id == cnid.Value))
                {
                    return RedirectToAction("Error", "Home");
                }

                ViewBag.CreatePermitted = IsPermitted(o => o.AllowCreateCheatNoteItems);
                ViewBag.EditPermitted = IsPermitted(o => o.AllowEditCheatNotes);

                return View(db.CheatNoteItems.List( l => l.Where(CheatNotesContextHelper.GetListConditions(cnid.Value, new CheatNotesContextOptions(showDeleted ?? false))).OrderBy(x => x.Position)));
            }
        }

        //
        // GET: /CheatNoteItems/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            using (var db = new CheatNotesContext())
            {
                ViewBag.EditPermitted = IsPermitted(o => o.AllowEditCheatNoteItems);
                ViewBag.DeletePermitted = IsPermitted(o => o.AllowDeleteCheatNoteItems);

                return View(db.CheatNoteItems.Get(id));
            }
        }

        //
        // GET: /CheatNoteItems/Create
        [Authorize]
        [PermissionRequired]
        public ActionResult Create(int cnid)
        {
            return View(new CheatNoteItem
                            {
                                CheatNoteId = cnid,
                                Position = GetDefaultItemPosition(cnid)
                            });
        } 

        //
        // POST: /CheatNoteItems/Create

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        [ValidateInput(false)]
        public ActionResult Create(CheatNoteItem cheatNoteItem)
        {
            try
            {
                using (var db = new CheatNotesContext())
                {
                    cheatNoteItem.CreatedById = GetCurrentUserId();

                    cheatNoteItem.Title = cheatNoteItem.Title.AntiCodeInjection();
                    cheatNoteItem.Content = cheatNoteItem.Content.AntiCodeInjection();

                    db.CheatNoteItems.Add(cheatNoteItem);
                    db.SaveChanges();
                }

                return RedirectToItemList(cheatNoteItem.CheatNoteId, cheatNoteItem.Position);
                //return RedirectToAction("List", new { cnid = cheatNoteItem.CheatNoteId });
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /CheatNoteItems/Edit/5

        [Authorize]
        [PermissionRequired]
        public ActionResult Edit(int id)
        {
            using (var db = new CheatNotesContext())
            {
                var item = db.CheatNoteItems.Get(id);

                var nextItem = db.CheatNoteItems.OrderBy(x => x.Position).FirstOrDefault(x => x.CheatNoteId == item.CheatNoteId && x.Position > item.Position);

                ViewBag.NextItemId = nextItem == null ? null : (int?)nextItem.Id;

                return View(item);
            }
        }

        //
        // POST: /CheatNoteItems/Edit/5

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        [ValidateInput(false)]
        [MultipleButton(Name = "action", Argument = "Edit")]
        public ActionResult Edit(int id, CheatNoteItem cheatNoteItem, int? nextItemId)
        {
            return Save(id, cheatNoteItem, null);
        }

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        [ValidateInput(false)]
        [MultipleButton(Name = "action", Argument = "Next")]
        public ActionResult Next(int id, CheatNoteItem cheatNoteItem, int? nextItemId)
        {
            return Save(id, cheatNoteItem, nextItemId);
        }

        private ActionResult Save(int id, CheatNoteItem cheatNoteItem, int? nextItemId)
        {
            try
            {
                using (var db = new CheatNotesContext())
                {
                    var instance = db.CheatNoteItems.Get(id);

                    instance.Position = cheatNoteItem.Position;
                    instance.Title = cheatNoteItem.Title.AntiCodeInjection();
                    instance.Content = cheatNoteItem.Content.AntiCodeInjection();
                    instance.DateModified = DateTime.Now;
                    instance.ModifiedById = GetCurrentUserId();

                    db.SaveChanges();
                }

                return nextItemId.HasValue
                    ? RedirectToAction("Edit", new { id = nextItemId.Value })
                    : RedirectToItemList(cheatNoteItem.CheatNoteId, cheatNoteItem.Position);
                //return RedirectToAction("List", new { cnid = cheatNoteItem.CheatNoteId });
            }
            catch
            {
                return View();
            }
        }

        //
        // POST: /CheatNoteItems/Delete/5

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        public ActionResult Delete(int id, CheatNoteItem cheatNoteItem)
        {
            return SetInstanceDeleted(id, cheatNoteItem);
        }

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        public ActionResult Restore(int id, CheatNoteItem cheatNoteItem)
        {
            return SetInstanceDeleted(id, cheatNoteItem, false);
        }

        [Authorize]
        public ActionResult CheatNoteInfo(int cnid, bool? toDetails)
        {
            using (var db = new CheatNotesContext())
            {
                return PartialView(toDetails.HasValue && toDetails.Value ? "_CheatNoteInfoToDetailsControl" : "_CheatNoteInfoToListControl", db.CheatNotes.Find(cnid));
            }
        }

        #region Private Helpers

        private ActionResult SetInstanceDeleted(int id, CheatNoteItem cheatNoteItem, bool isDeleted = true)
        {
            try
            {
                SetInstanceDeleted(db => db.CheatNoteItems, id, isDeleted);

                return RedirectToItemList(cheatNoteItem.CheatNoteId, cheatNoteItem.Position);
                //return RedirectToAction("List", new { cnid = cheatNoteItem.CheatNoteId });
            }
            catch
            {
                return RedirectToItemList(cheatNoteItem.CheatNoteId, cheatNoteItem.Position);
                //return RedirectToAction("List", new { cnid = cheatNoteItem.CheatNoteId });
            }
        }

        private static int GetDefaultItemPosition(int cnid)
        {
            using (var db = new CheatNotesContext())
            {
                var maxPos = db.CheatNoteItems.Where(x => !x.DateDeleted.HasValue && x.CheatNoteId == cnid).Max(x => (int?)x.Position);

                return (maxPos.HasValue && maxPos.Value > 0) ? maxPos.Value + 1 : 1;
            }
        }

        private ActionResult RedirectToItemList(int cnid, int? position)
        {
            var positionAnchor = position.HasValue
                                     ? string.Format("#{0}", position.Value)
                                     : string.Empty;

            //return RedirectToAction("List", new { cnid });
            return new RedirectResult(Url.Action("List", new { cnid }) + positionAnchor);
        }

        #endregion
    }
}

CheatNoteMaker/CheatNoteMaker/Views/CheatNotes/Create.cshtml
@model CheatNoteMaker.Models.CheatNotes.CheatNote

@{
    ViewBag.Title = "Новая шпаргалка";
}
@Html.Partial("_BackToCheatNoteList")
<h2>Новая шпаргалка</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Create", "CheatNotes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Новая шпаргалка</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        @*<div class="editor-label">
            @Html.Label("Загрузить текстовый файл с вопросами (каждый вопрос должен быть на отдельной строке)")
        </div>
        <div class="editor-field">
            <input type="file" name="file" id="file" />
        </div>*@
    </fieldset>
    <fieldset>
            <legend>Список вопросов (одна строка - один вопрос, может начинаться с номера)</legend>
            
            <div class="editor-field">
                @Html.Editor("questionsPlainText", "MultilineText", "questionsPlainText")
            </div>
        </fieldset>
    <p>
        <input type="submit" value="Добавить" />
    </p>
}
@Html.Partial("_BackToCheatNoteList")

CheatNoteMaker/CheatNoteMaker/Views/CheatNotes/Details.cshtml
@model CheatNoteMaker.Models.CheatNotes.CheatNote

@{
    ViewBag.Title = "Подробности";
}
@Html.Partial("_BackToCheatNoteList")
<h2>@Html.DisplayFor(model => model.Name)</h2>

@if (ViewBag.GeneratorPermitted)
{
    <p>
        <b>
            @Html.ActionLink("Генератор HTML файлов", "GenerateHtmlFiles", "CheatNoteHtmlGenerator", new { id = Model.Id }, new { @class = "great_btn" })
        </b>
    </p>
}

<p>
    <b>
        @Html.ActionLink("Смотреть список вопросов", "List", "CheatNoteItems", new { cnid = Model.Id }, null)
    </b>
</p>
<fieldset>
    <legend>Описание</legend>
    
    <div class="display-field">
        @Html.Raw(Html.Encode(Model.Description).Replace("\n", "<br />"))
    </div>
</fieldset>

@Html.Partial("_ObjectBaseDetails", Model)
@if (ViewBag.EditPermitted == true)
{
    <p>
        @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }, new { @class = "great_btn" })    
    </p>
}
@if (ViewBag.DeletePermitted == true)
{
    if (Model.DateDeleted.HasValue)
     {
         using (Html.BeginForm("Restore", "CheatNotes", FormMethod.Post))
         {
             @Html.HiddenFor(model => model.Id)

             <p>
                 <input type="submit" value="Восстановить шпаргалку" onclick=" return confirmRestore(); " />
             </p>
         }
     }
     else
     {
         using (Html.BeginForm("Delete", "CheatNotes", FormMethod.Post))
         {
             @Html.HiddenFor(model => model.Id)

             <p>
                 <input type="submit" value="Удалить шпаргалку" onclick=" return confirmDelete(); " />
             </p>
         }
     }
}
@Html.Partial("_BackToCheatNoteList")

CheatNoteMaker/CheatNoteMaker/Views/CheatNotes/Edit.cshtml
@model CheatNoteMaker.Models.CheatNotes.CheatNote

@{
    ViewBag.Title = "Редактирование шпаргалки";
}
@Html.Partial("_BackToCheatNoteList")
<h2>Редактирование шпаргалки</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Редактирование шпаргалки</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        @Html.HiddenFor(model => model.Id)
        
        <p>
            <input type="submit" value="Сохранить" />
        </p>
    </fieldset>
}
@Html.Partial("_BackToCheatNoteList")

CheatNoteMaker/CheatNoteMaker/Views/CheatNotes/Index.cshtml
@using CheatNoteMaker.BusinessLogic.Extensions
@model IEnumerable<CheatNoteMaker.Models.CheatNotes.CheatNote>

@{
    ViewBag.Title = "Шпаргалки";
}

<h2>Шпаргалки</h2>

@if (ViewBag.CreatePermitted == true)
{
    <p>
        @Html.ActionLink("Создать новую шпаргалку", "Create", null, new { @class = "great_btn" })
    </p>
}
@if (Model.Any())
{
    <table>
        <tr>
            <th>
                Название
            </th>
            <th>
                Описание
            </th>
            <th>@("true".Equals(this.Request["showDeleted"], StringComparison.InvariantCultureIgnoreCase) ? this.Html.ActionLink("Скрыть удалённые", "Index") : this.Html.ActionLink("Показать удалённые", "Index", "CheatNotes", new { showDeleted = true }, null))</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @if (item.DateDeleted.HasValue)
                    {
                        <s>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</s>
                    }
                    else
                    {
                        @Html.ActionLink(item.Name, "Details", new { id = item.Id })
                    }
                </td>
                <td>
                    @if (item.DateDeleted.HasValue)
                    {
                        <b>[удалено @item.DateDeleted.Value]</b>
                    }
                    else
                    {
                        @Html.Label(string.Empty, item.Description.Shorten(40))
                    }
                </td>
                <td>
                    @Html.ActionLink("Список вопросов", "List", "CheatNoteItems", new { cnid = item.Id }, null)
                </td>
            </tr>
        }

    </table>
    if (ViewBag.CreatePermitted == true)
    {
         <p>
             @Html.ActionLink("Создать новую шпаргалку", "Create", null, new { @class = "great_btn" })
         </p>
     }
}
else
{

    if ("true".Equals(this.Request["showDeleted"], StringComparison.InvariantCultureIgnoreCase))
    {
        <b>А, нет, точно пусто!</b>
    }
    else
    {
        <b>Похоже, ещё не создано ни одной шпаргалки или все удалены.</b>
        @Html.ActionLink("Показать удалённые", "Index", "CheatNotes", new { showDeleted = true }, null)
    }
}