CheatNoteMaker/CheatNoteMaker/Controllers/CheatNotes/CheatNotesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

using CheatNoteMaker.BusinessLogic.CustomAttributes;
using CheatNoteMaker.BusinessLogic.Extensions;
using CheatNoteMaker.Models;
using CheatNoteMaker.Models.CheatNotes;

namespace CheatNoteMaker.Controllers.CheatNotes
{
    public class CheatNotesController : BaseController
    {
        //
        // GET: /CheatNote/
        [Authorize]
        public ActionResult Index(bool? showDeleted)
        {
            using (var db = new CheatNotesContext())
            {
                ViewBag.CreatePermitted = IsPermitted(o => o.AllowCreateCheatNotes);
                //return View(db.CheatNotes.IncludeBase().Where(CheatNotesContextHelper.GetListConditions(new CheatNotesContextOptions(showDeleted ?? false))).OrderByDescending(x => x.DateModified).ToList());
                return View(db.CheatNotes.List(l => l.Where(CheatNotesContextHelper.GetListConditions(new CheatNotesContextOptions(showDeleted ?? false))).OrderByDescending(x => x.DateModified)));
            }
        }

        //
        // GET: /CheatNote/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            ViewBag.GeneratorPermitted = IsPermitted(p => p.AllowGenerateCheatNoteHtml);
            ViewBag.EditPermitted = IsPermitted(o => o.AllowEditCheatNotes);
            ViewBag.DeletePermitted = IsPermitted(o => o.AllowDeleteCheatNotes);

            using (var db = new CheatNotesContext())
            {
                return View(db.CheatNotes.Get(id));
            }
        }

        //
        // GET: /CheatNote/Create
        [Authorize]
        [PermissionRequired]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /CheatNote/Create

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        public ActionResult Create(CheatNote cheatNote, string questionsPlainText)
        {
            try
            {
                var cheatNoteItems = ParseCheatNoteItems(questionsPlainText);

                if (cheatNoteItems != null && cheatNoteItems.Count > 0)
                {
                    foreach (var item in cheatNoteItems)
                    {
                        item.CreatedById = GetCurrentUserId();
                    }

                    cheatNote.Items = cheatNoteItems;
                }

                using (var db = new CheatNotesContext())
                {
                    cheatNote.CreatedById = GetCurrentUserId();

                    db.CheatNotes.Add(cheatNote);
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View(cheatNote);
            }
        }

        [Authorize]
        [PermissionRequired]
        public ActionResult Edit(int id)
        {
            using (var db = new CheatNotesContext())
            {
                return View(db.CheatNotes.Get(id));
            }
        }

        //
        // POST: /CheatNote/Edit/5

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        public ActionResult Edit(int id, CheatNote cheatNote)
        {
            try
            {
                using (var db = new CheatNotesContext())
                {
                    var instance = db.CheatNotes.Get(id);

                    if (instance != null)
                    {
                        instance.Name = cheatNote.Name;
                        instance.Description = cheatNote.Description;
                        instance.DateModified = DateTime.Now;
                        instance.ModifiedById = GetCurrentUserId();
                    }

                    db.Entry(instance).State = EntityState.Modified;
                    db.SaveChanges();
                }
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // POST: /CheatNote/Delete/5

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        public ActionResult Delete(int id)
        {
            return SetInstanceDeleted(id);
        }

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        public ActionResult Restore(int id)
        {
            return SetInstanceDeleted(id, false);
        }

        #region Private Helpers

        private ActionResult SetInstanceDeleted(int id, bool isDeleted = true)
        {
            try
            {
                SetInstanceDeleted(db => db.CheatNotes, id, isDeleted);

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        private static ICollection<CheatNoteItem> ParseCheatNoteItems(HttpPostedFileBase file)
        {
            if (file == null || file.ContentLength <= 0 || !file.ContentType.Equals("text/plain"))
            {
                return null;
            }

            using (var sr = new StreamReader(file.InputStream, Encoding.Default))
            {
                return ParseCheatNoteItems(sr.ReadToEnd());
            }
        }

        private static ICollection<CheatNoteItem> ParseCheatNoteItems(string content)
        {
            if (string.IsNullOrWhiteSpace(content))
            {
                return null;
            }

            var lines = content.Replace("\r", string.Empty).Split(new[] { "\n" }, StringSplitOptions.RemoveEmptyEntries);

            if (!lines.Any())
            {
                return null;
            }

            var items = new List<CheatNoteItem>();

            var globalNumber = 1;

            var splittingChars = new[] { ' ', '.', ',', ':', ';', '/', '?', ':', '#', '№', '!', '*', '^', '%', '$', '-', '=', ')' };

            foreach (var line in lines)
            {
                var numberAndText = line.TrimStart(splittingChars).Trim().Split(splittingChars, 2, StringSplitOptions.RemoveEmptyEntries);

                var number = 0;
                var numberParsed = false;
                var text = string.Empty;

                if (numberAndText.Length > 1)
                {
                    numberParsed = int.TryParse(numberAndText[0], out number);

                    text = numberParsed ? numberAndText[1].Trim() : line.Trim();
                }
                else if (numberAndText.Length > 0)
                {
                    text = line.Trim();
                }

                items.Add(new CheatNoteItem
                            {
                                Position = numberParsed ? number : globalNumber,
                                Title = text
                            });

                globalNumber++;
            }

            return items;
        }

        #endregion
    }
}

CheatNoteMaker/CheatNoteMaker/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CheatNoteMaker.BusinessLogic.CustomAttributes;
using CheatNoteMaker.Controllers.CheatNotes;
using CheatNoteMaker.Models;
using CheatNoteMaker.Models.Users;
using System.Data.Entity;

namespace CheatNoteMaker.Controllers
{
    public class UserManagementController : BaseController
    {
        //
        // GET: /UserManagement/
        [Authorize]
        [PermissionRequired]
        public ActionResult Index()
        {
            using (var db = new CheatNotesContext())
            {
                ViewBag.CurrentUserId = GetCurrentUserId();

                return View(db.UserInfos.Include(x => x.Permissions).ToList());
            }
        }
        
        ////
        //// GET: /UserManagement/Create

        //public ActionResult Create()
        //{
        //    return View();
        //} 

        ////
        //// POST: /UserManagement/Create

        //[HttpPost]
        //public ActionResult Create(UserInfo userInfo)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //public ActionResult UserInfoPermissionsRow(int id)
        //{
        //    try
        //    {
        //        //var userPermissions = user.Permissions;
        //        using (var db = new CheatNotesContext())
        //        {
        //            var userInfo = db.UserInfos.Include(x => x.Permissions).FirstOrDefault(u => u.Id == id);

        //            return PartialView(userInfo);
        //        }
        //    }
        //    catch
        //    {
        //        return null;
        //    }
        //}

        [HttpPost]
        [Authorize]
        [PermissionRequired]
        public ActionResult Update(UserInfo userInfo)
        {
            try
            {
                var userPermissions = userInfo.Permissions;

                if (userInfo.Id == this.GetCurrentUserId())
                {
                    userPermissions.AllowManageUsers = true;
                }

                using (var db = new CheatNotesContext())
                {
                    var permissions = db.UserPermissions.FirstOrDefault(p => p.Id == userPermissions.Id);

                    if (permissions != null)
                    {
                        permissions.UpdateData(userPermissions);

                        db.Entry(permissions).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }
            }
            catch
            {
            }

            return RedirectToAction("Index");
        }

        ////
        //// GET: /UserManagement/Delete/5

        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        ////
        //// POST: /UserManagement/Delete/5

        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

CheatNoteMaker/CheatNoteMaker/Views/Shared/_BackToCheatNoteItemList.cshtml
@if (Model != null)
{
    <p>
        @*@Html.ActionLink("<- Назад к списку вопросов", "List", "CheatNoteItems", new { cnid = Model.CheatNoteId }, null)*@
        <a href="@Url.Action("List", "CheatNoteItems", new { cnid = Model.CheatNoteId })@(ViewBag.CheatNoteItemListPosition == null ? string.Empty : string.Format("#{0}", ViewBag.CheatNoteItemListPosition))">&lt;- Назад к списку вопросов</a>
    </p>
}

CheatNoteMaker/CheatNoteMaker/Views/Shared/_BackToCheatNoteList.cshtml
<p>
    @Html.ActionLink("<- Назад к списку шпаргалок", "Index", "CheatNotes")
</p>

CheatNoteMaker/CheatNoteMaker/Views/Shared/_CheatNoteInfoToDetailsControl.cshtml
@model CheatNoteMaker.Models.CheatNotes.CheatNote

@if (Model != null)
{
    @Html.ActionLink(Model.Name, "Details", "CheatNotes", new { id = Model.Id }, null)
}

CheatNoteMaker/CheatNoteMaker/Views/Shared/_CheatNoteInfoToListControl.cshtml
@model CheatNoteMaker.Models.CheatNotes.CheatNote

@if (Model != null)
{
    @Html.ActionLink(Model.Name, "List", "CheatNoteItems", new { cnid = Model.Id }, null)
}

CheatNoteMaker/CheatNoteMaker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/common.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>@Html.ActionLink("Шпородел", "Index", "CheatNotes", null, new { style = "text-decoration: none; color: white;"})</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Шпаргалки", "Index", "CheatNotes")</li>
                    <li>@Html.ActionLink("Управление пользователями", "Index", "UserManagement")</li>
                    <li>@Html.ActionLink("Где я?", "About", "Home")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

CheatNoteMaker/CheatNoteMaker/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Привет, <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Выход", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Вход", "LogOn", "Account") ]
}

CheatNoteMaker/CheatNoteMaker/Views/Shared/_ObjectBaseDetails.cshtml
@model CheatNoteMaker.Models.Common.ObjectBase
<fieldset>
    <legend>Дополнительно</legend>
<div class="display-label">Дата создания</div>
<div class="display-field">
    @Html.DisplayFor(model => model.DateCreated)
    @if (Model.CreatedBy != null)
    {
        @Html.Label(string.Empty, string.Format("({0})", Model.CreatedBy))
    }
</div>
    
@if (Model.DateModified != Model.DateCreated)
{
    <div class="display-label">Дата изменения</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateModified)
        @if (Model.ModifiedBy != null)
        {
            @Html.Label(string.Empty, string.Format("({0})", Model.ModifiedBy))
        }
    </div>
}

@if (Model.DateDeleted.HasValue)
{
    <div class="display-label">Дата удаления</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateDeleted)
        @if (Model.DeletedBy != null)
        {
            @Html.Label(string.Empty, string.Format("({0})", Model.DeletedBy))
        }
    </div>
}
</fieldset>